export type Placement = {
  id: string;
  platform: string;
  label: string;
  ratio: string;
  width: number;
  height: number;
  device: "iphone" | "android" | "desktop";
  overlay: "instagram" | "tiktok" | "youtube" | "snapchat" | "linkedin" | "web";
  safeZones: Array<{
    id: string;
    label: string;
    x: number;
    y: number;
    width: number;
    height: number;
  }>;
};

export const placements: Placement[] = [
  {
    id: "meta-feed",
    platform: "META",
    label: "Feed",
    ratio: "1:1",
    width: 1080,
    height: 1080,
    device: "iphone",
    overlay: "instagram",
    safeZones: [
      { id: "caption", label: "Caption rail", x: 0, y: 82, width: 100, height: 18 },
    ],
  },
  {
    id: "meta-stories",
    platform: "META",
    label: "Stories/Reels",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "iphone",
    overlay: "instagram",
    safeZones: [
      { id: "top-ui", label: "Profile header", x: 0, y: 0, width: 100, height: 13 },
      { id: "bottom-cta", label: "Swipe CTA", x: 0, y: 86, width: 100, height: 14 },
    ],
  },
  {
    id: "meta-marketplace",
    platform: "META",
    label: "Marketplace",
    ratio: "1:1",
    width: 1080,
    height: 1080,
    device: "iphone",
    overlay: "instagram",
    safeZones: [{ id: "bottom-meta", label: "Action controls", x: 0, y: 84, width: 100, height: 16 }],
  },
  {
    id: "meta-right-column",
    platform: "META",
    label: "Right Column",
    ratio: "1.91:1",
    width: 1200,
    height: 628,
    device: "desktop",
    overlay: "web",
    safeZones: [{ id: "browser-chrome", label: "Browser chrome", x: 0, y: 0, width: 100, height: 10 }],
  },
  {
    id: "tiktok-in-feed",
    platform: "TIKTOK",
    label: "In-Feed Ads",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "android",
    overlay: "tiktok",
    safeZones: [
      { id: "right-actions", label: "Like/share stack", x: 83, y: 38, width: 17, height: 40 },
      { id: "caption", label: "Caption + CTA", x: 0, y: 78, width: 100, height: 22 },
    ],
  },
  {
    id: "tiktok-topview",
    platform: "TIKTOK",
    label: "TopView",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "android",
    overlay: "tiktok",
    safeZones: [
      { id: "right-actions", label: "Like/share stack", x: 83, y: 40, width: 17, height: 38 },
      { id: "bottom-cta", label: "CTA rail", x: 0, y: 82, width: 100, height: 18 },
    ],
  },
  {
    id: "tiktok-branded",
    platform: "TIKTOK",
    label: "Branded Content",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "android",
    overlay: "tiktok",
    safeZones: [
      { id: "brand-disclosure", label: "Disclosure + profile", x: 0, y: 0, width: 100, height: 12 },
      { id: "right-actions", label: "Engagement buttons", x: 84, y: 42, width: 16, height: 34 },
    ],
  },
  {
    id: "gdn-300x250",
    platform: "GOOGLE",
    label: "GDN 300x250",
    ratio: "300x250",
    width: 300,
    height: 250,
    device: "desktop",
    overlay: "web",
    safeZones: [{ id: "adchoices", label: "AdChoices corner", x: 86, y: 0, width: 14, height: 12 }],
  },
  {
    id: "gdn-728x90",
    platform: "GOOGLE",
    label: "GDN 728x90",
    ratio: "728x90",
    width: 728,
    height: 90,
    device: "desktop",
    overlay: "web",
    safeZones: [{ id: "adchoices", label: "AdChoices corner", x: 94, y: 0, width: 6, height: 22 }],
  },
  {
    id: "gdn-160x600",
    platform: "GOOGLE",
    label: "GDN 160x600",
    ratio: "160x600",
    width: 160,
    height: 600,
    device: "desktop",
    overlay: "web",
    safeZones: [{ id: "adchoices", label: "AdChoices corner", x: 72, y: 0, width: 28, height: 7 }],
  },
  {
    id: "gdn-320x50",
    platform: "GOOGLE",
    label: "GDN 320x50",
    ratio: "320x50",
    width: 320,
    height: 50,
    device: "android",
    overlay: "web",
    safeZones: [{ id: "adchoices", label: "AdChoices corner", x: 88, y: 0, width: 12, height: 34 }],
  },
  {
    id: "gdn-300x600",
    platform: "GOOGLE",
    label: "GDN 300x600",
    ratio: "300x600",
    width: 300,
    height: 600,
    device: "desktop",
    overlay: "web",
    safeZones: [{ id: "adchoices", label: "AdChoices corner", x: 86, y: 0, width: 14, height: 6 }],
  },
  {
    id: "youtube-16x9",
    platform: "GOOGLE",
    label: "YouTube",
    ratio: "16:9",
    width: 1920,
    height: 1080,
    device: "desktop",
    overlay: "youtube",
    safeZones: [
      { id: "controls", label: "Playback controls", x: 0, y: 84, width: 100, height: 16 },
    ],
  },
  {
    id: "youtube-shorts",
    platform: "GOOGLE",
    label: "YouTube Shorts",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "android",
    overlay: "youtube",
    safeZones: [
      { id: "shorts-actions", label: "Shorts action rail", x: 82, y: 36, width: 18, height: 45 },
      { id: "bottom-title", label: "Title controls", x: 0, y: 82, width: 100, height: 18 },
    ],
  },
  {
    id: "snap-top-snap",
    platform: "SNAPCHAT",
    label: "Top Snap",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "iphone",
    overlay: "snapchat",
    safeZones: [
      { id: "top-snap", label: "Snap header", x: 0, y: 0, width: 100, height: 12 },
      { id: "bottom-snap", label: "Swipe up CTA", x: 0, y: 86, width: 100, height: 14 },
    ],
  },
  {
    id: "snap-story-ad",
    platform: "SNAPCHAT",
    label: "Story Ad",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    device: "iphone",
    overlay: "snapchat",
    safeZones: [
      { id: "story-header", label: "Story header", x: 0, y: 0, width: 100, height: 12 },
      { id: "story-cta", label: "CTA", x: 0, y: 84, width: 100, height: 16 },
    ],
  },
  {
    id: "linkedin-single-wide",
    platform: "LINKEDIN",
    label: "Single Image Ad",
    ratio: "1.91:1",
    width: 1200,
    height: 628,
    device: "desktop",
    overlay: "linkedin",
    safeZones: [{ id: "linkedin-actions", label: "Social action row", x: 0, y: 88, width: 100, height: 12 }],
  },
  {
    id: "linkedin-single-square",
    platform: "LINKEDIN",
    label: "Single Image Ad",
    ratio: "1:1",
    width: 1080,
    height: 1080,
    device: "desktop",
    overlay: "linkedin",
    safeZones: [{ id: "linkedin-actions", label: "Social action row", x: 0, y: 88, width: 100, height: 12 }],
  },
  {
    id: "linkedin-sponsored",
    platform: "LINKEDIN",
    label: "Sponsored Content",
    ratio: "1.91:1",
    width: 1200,
    height: 628,
    device: "desktop",
    overlay: "linkedin",
    safeZones: [{ id: "sponsored-controls", label: "Sponsored controls", x: 0, y: 86, width: 100, height: 14 }],
  },
  {
    id: "native-custom",
    platform: "NATIVE/WEB",
    label: "Custom Aspect Ratios",
    ratio: "User-defined",
    width: 1200,
    height: 800,
    device: "desktop",
    overlay: "web",
    safeZones: [],
  },
];

export const languages = [
  { code: "EN", label: "English" },
  { code: "DE", label: "German" },
  { code: "FR", label: "French" },
  { code: "IT", label: "Italian" },
  { code: "ES", label: "Spanish" },
  { code: "PT", label: "Portuguese" },
  { code: "TR", label: "Turkish" },
  { code: "AR", label: "Arabic", rtl: true },
  { code: "ZH", label: "Chinese" },
  { code: "JA", label: "Japanese" },
];

export const outputFormats = ["Original", "PNG", "JPG", "WebP", "PDF"];
